### ISSUE TITLE
Rebuild utfcpp 2.3.4

### ISSUE THREAD

**Issue by karenzshea** [mapbox/mason#313] opened 2017-01-05 19:21 UTC
The `mason.ini` file is somehow not getting built for utfcpp package, resulting in cmake errors like `configuration file not found for utfcpp`

If utfcpp is due for a rebuild, this could use looking into.

cc @springmeyer

**Comment by springmeyer** [comment] 2017-01-05 19:24
This is the second package we've encountered with a busted `mason.ini`. Probably worth writing a script to try to autodetect other packages with blank `mason.ini`.

**Comment by springmeyer** [comment] 2017-01-05 19:32
Actually looks like utfcpp is just missing a `mason.ini` which is the intended behavior for old packages not rebuilt after https://github.com/mapbox/mason/pull/176. The problem is likely that the fallback to pkg-config failed. I've rebuilt the package now so will close this issue (not going to worry about debugging why the pkg-config fallback may have failed).

**Closed by springmeyer** 2017-01-05 19:32 UTC
