### ISSUE TITLE
Self-compiled clang orders of magnitude slower than Ubuntu version

### ISSUE THREAD

**Issue by TheMarex** [mapbox/mason#183] opened 2016-06-02 09:28 UTC
For `osrm-backend` we see slowdowns that make the build time out. https://travis-ci.org/Project-OSRM/osrm-backend/jobs/134608531#L2145

Looking at the compile flags it seems we are not enabling all optimizations. Here is what ubuntu uses to compile clang:

```
		cd $(TARGET_BUILD) && \
		cmake ../ \
		-DCMAKE_INSTALL_PREFIX=/usr/lib/llvm-$(LLVM_VERSION) \
		-DCMAKE_VERBOSE_MAKEFILE=ON \
		-DCMAKE_BUILD_TYPE=RelWithDebInfo \
		-DCMAKE_CXX_FLAGS=$(CXXFLAGS_EXTRA) \
		-DLLVM_LINK_LLVM_DYLIB=ON \
		-DLLVM_VERSION_SUFFIX= \
		-DLLVM_ENABLE_SPHINX=ON \
		-DLLVM_ENABLE_RTTI=ON \
		-DLLVM_ENABLE_FFI=ON \
		$(CMAKE_EXTRA) \
		-DLIBCLANG_LIBRARY_VERSION=$(SONAME_EXT); \
```

Interesting flags seem to be:

```
		-DLLVM_ENABLE_RTTI=ON \
		-DLLVM_ENABLE_FFI=ON \
```

/cc @springmeyer

**Comment by springmeyer** [comment] 2016-06-02 18:23
Thank you @TheMarex - I'll enable RTTI and FFI and see if that helps!

**Comment by springmeyer** [comment] 2016-06-02 18:29
Locally on OS X I'm seeing that `-ON and -DNDEBUG` are missing from some of the compile flags. If that is also happening on linux that would surely explain the problem.

**Comment by springmeyer** [comment] 2016-06-02 20:31
Yep, confirmed the binaries were incorrectly ending up as Debug builds rather than Release. This is now fixed for `clang-3.8`: https://github.com/mapbox/mason/commit/725cbaf27f9379957653a7e81fb255c327594c6b fixed but I'll fix properly now by avoiding using `CMAKE_CXX_FLAGS_RELEASE` (which I now realize overrides rather than appends to the default Release flags). The download for osrm-backend now dropped from 70s to 10s and the build should go a lot faster: https://travis-ci.org/Project-OSRM/osrm-backend/jobs/134608531

**Comment by springmeyer** [comment] 2016-06-02 20:49
Looks like this new clang-3.8 is newly enabling a cmake configure line to pass. Previous clang-3.8 builds did not support openmp but now we're seeing:

```
OpenMP support found. Linking just in case for stxxl
```

but then also:

```
$ ./unit_tests/server-tests
./unit_tests/server-tests: error while loading shared libraries: libomp.so: cannot open shared object file: No such file or directory
```

**Comment by springmeyer** [comment] 2016-06-03 04:23
Openmp issue solved by removing support in the binaries.

**Closed by springmeyer** 2016-06-03 04:23 UTC
