### ISSUE TITLE
Unable to install geojson with Xcode 8

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mason#229] opened 2016-08-12 05:05 UTC
If I use `xcode-select` to select Xcode 8, I’m unable to install the dependencies needed for mapbox-gl-native’s `iproj` make rule, because no iOS 10.0 binary is available for geojson 0.1.4:

```
-- [Mason] Downloading package https://mason-binaries.s3.amazonaws.com/ios-10.0/geojson/0.1.4.tar.gz...
CMake Error at .mason/mason.cmake:113 (message):
  [Mason] Failed to download
  https://mason-binaries.s3.amazonaws.com/ios-10.0/geojson/0.1.4.tar.gz:
  curl: (22) The requested URL returned error: 403 Forbidden

Call Stack (most recent call first):
  CMakeLists.txt:34 (mason_use)
```

This issue doesn’t reproduce when running the `xproj` make rule, because Mason is parameterizing on architecture instead of macOS version:

```
-- [Mason] Downloading package https://mason-binaries.s3.amazonaws.com/osx-x86_64/geojson/0.1.4.tar.gz...
-- [Mason] Unpacking package to mason_packages/osx-x86_64/geojson/0.1.4...
```

/cc @kkaefer @friedbunny

**Comment by kkaefer** [comment] 2016-08-12 09:08
Duplicate of https://github.com/mapbox/mason/issues/144

**Closed** 2017-01-18 22:01 UTC
Labels: bug
